// TripTap Data: Cities, Listings (Stays, Wheels, Experiences), and Business Ads

const ethiopianCities = [
  { id: 'all', nameEn: 'All Ethiopia', nameAm: 'መላው ኢትዮጵያ', nameAr: 'كل إثيوبيا', count: 24 },
  { id: 'addis', nameEn: 'Addis Ababa', nameAm: 'አዲስ አበባ', nameAr: 'أديس أبابا', count: 10, lat: 9.02497, lng: 38.74689 },
  { id: 'bahirdar', nameEn: 'Bahir Dar', nameAm: 'ባህር ዳር', nameAr: 'بحر دار', count: 4, lat: 11.59364, lng: 37.39077 },
  { id: 'hawassa', nameEn: 'Hawassa', nameAm: 'ሀዋሳ', nameAr: 'هواسا', count: 3, lat: 7.06205, lng: 38.47631 },
  { id: 'lalibela', nameEn: 'Lalibela', nameAm: 'ላሊበላ', nameAr: 'لاليبيلا', count: 3, lat: 12.03219, lng: 39.04756 },
  { id: 'gondar', nameEn: 'Gondar', nameAm: 'ጎንደር', nameAr: 'غوندار', count: 2, lat: 12.60751, lng: 37.46672 },
  { id: 'bishoftu', nameEn: 'Bishoftu', nameAm: 'ቢሾፍቱ', nameAr: 'بيشوفتو', count: 2, lat: 8.75225, lng: 38.97846 }
];

const sponsoredAds = [
  {
    id: 'ad-1',
    businessName: 'Kuriftu Resort & Spa Bishoftu',
    badge: 'Premium Partner',
    tier: 'premium',
    duration: 10000,
    taglineEn: 'Luxury Lakeside Retreats — Exclusive 15% discount when booked via Telebirr on TripTap',
    taglineAm: 'የቅንጦት የሀይቅ ዳር እረፍት — በTripTap በቴሌብር ሲያስይዙ የ15% ቅናሽ',
    taglineAr: 'منتجع كورفتو الفاخر بيشوفتو — خصم حصري 15% عند الحجز عبر تيليبير على تريب تﺎب',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
    link: '#stays',
    ctaEn: 'Explore Stays',
    ctaAm: 'ማረፊያዎችን እይ',
    ctaAr: 'استكشف الإقامات'
  },
  {
    id: 'ad-2',
    businessName: 'Ethio Express 4x4 Car Rentals',
    badge: 'Standard Partner',
    tier: 'standard',
    duration: 5000,
    taglineEn: 'Rugged Land Cruisers with licensed English & Amharic speaking drivers for Omo Valley & Highlands',
    taglineAm: 'አስተማማኝ ቶዮታ ላንድ ክሩዘር ከመንጃ ፍቃድ ካላቸው ልምድኛ ሹፌሮች ጋር',
    taglineAr: 'تأجير سيارات الدفع الرباعي 4x4 مع سائقين محترفين لجولات الوادي والرحلات الجبلية',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    link: '#wheels',
    ctaEn: 'Rent Wheels',
    ctaAm: 'ተሽከርካሪዎችን እይ',
    ctaAr: 'استئجر سيارة'
  },
  {
    id: 'ad-3',
    businessName: 'Tomoca Heritage Coffee Ceremonies',
    badge: 'Basic Partner',
    tier: 'basic',
    duration: 3000,
    taglineEn: 'Authentic Ethiopian clay pot jebena coffee brewing and cultural roasting workshops',
    taglineAm: 'ባህላዊ የሸክላ ጀበና የኢትዮጵያ ቡና አፈላል እና የባህል ዝግጅት',
    taglineAr: 'جلسات تحضير القهوة الإثيوبية التقليدية العريقة بالجَبَنَة وورش التحميص التراثية',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=80',
    link: '#experiences',
    ctaEn: 'Book Experience',
    ctaAm: 'ልምዱን ያስይዙ',
    ctaAr: 'احجز التجربة'
  }
];

const listingsData = [
  // ================= STAYS =================
  {
    id: 'stay-1',
    category: 'stays',
    subType: 'Villa',
    subTypeAm: 'ቪላ',
    subTypeAr: 'فيلا فاخرة',
    titleEn: 'Bole Atlas Luxury Executive Villa with Private Garden',
    titleAm: 'ቦሌ አትላስ የቅንጦት ኤክስኪዩቲቭ ቪላ ከግል የአትክልት ስፍራ ጋር',
    titleAr: 'فيلا رجال الأعمال الفاخرة في بولي أطلس مع حديقة خاصة',
    cityId: 'addis',
    cityNameEn: 'Bole, Addis Ababa',
    cityNameAm: 'ቦሌ አትላስ፣ አዲስ አበባ',
    cityNameAr: 'بولي أطلس، أديس أبابا',
    lat: 8.9953,
    lng: 38.7842,
    priceETB: 8500,
    priceUnit: 'night',
    rating: 4.95,
    reviewsCount: 38,
    instantBook: true,
    verifiedHost: true,
    trustScore: '99%',
    hostName: 'Dawit Mengistu',
    hostPhone: '+251 91 123 4567',
    hostTelebirr: '+251 91 123 4567',
    status: 'Available', // Available, Booked, On Maintenance
    cancellation: 'freeCancel',
    guestsMax: 6,
    bedrooms: 3,
    bathrooms: 3.5,
    amenities: ['generator', 'waterTank', 'wifi', 'kitchen', 'security', 'parking', 'ac'],
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=800&q=80'
    ],
    descriptionEn: 'Gated 3-bedroom sanctuary in Bole Atlas with 24/7 solar backup generator, automatic 5,000L water reserve, fiber optic 100Mbps WiFi, chef kitchen, and private terrace.',
    descriptionAm: 'በቦሌ አትላስ የሚገኝ ባለ 3 መኝታ ቤት ቪላ፣ 24/7 የፀሐይና ጀነሬተር ኤሌክትሪክ፣ የ5,000 ሊትር ውሃ ማጠራቀሚያ፣ ፈጣን ዋይፋይ እና የጥበቃ አገልግሎት ያለው።',
    descriptionAr: 'فيلا راقية من 3 غرف نوم في بولي أطلس مزودة بمولد كهربائي يعمل 24/7 وخزان مياه 5000 لتر وإنترنت ألياف ضوئية سريع وحراسة أمنية مشددة.'
  },
  {
    id: 'stay-2',
    category: 'stays',
    subType: 'Apartment',
    subTypeAm: 'አፓርታማ',
    subTypeAr: 'شقة فندقية',
    titleEn: 'Kazanchis Skyline Modern Condo near UNECA',
    titleAm: 'ካዛንቺስ ዘመናዊ ኮንዶ አፓርታማ ከተባበሩት መንግስታት ድርጅት (UNECA) አቅራቢያ',
    titleAr: 'شقة كازانتشيس العصرية المطلة على المدينة قرب مقر الأمم المتحدة',
    cityId: 'addis',
    cityNameEn: 'Kazanchis, Addis Ababa',
    cityNameAm: 'ካዛንቺስ፣ አዲስ አበባ',
    cityNameAr: 'كازانتشيس، أديس أبابا',
    lat: 9.0185,
    lng: 38.7695,
    priceETB: 4200,
    priceUnit: 'night',
    rating: 4.88,
    reviewsCount: 52,
    instantBook: true,
    verifiedHost: true,
    trustScore: '98%',
    hostName: 'Selamawit Tadesse',
    hostPhone: '+251 92 234 5678',
    hostTelebirr: '+251 92 234 5678',
    status: 'Available',
    cancellation: 'freeCancel',
    guestsMax: 3,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['generator', 'waterTank', 'wifi', 'kitchen', 'security', 'ac'],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=80'
    ],
    descriptionEn: 'High-floor sunlit flat with breathtaking views of the capital, uninterrupted power generator, water backup, and walking distance to UNECA and luxury dining.',
    descriptionAm: 'በካዛንቺስ የሚገኝ ውብ አፓርታማ፣ ጀነሬተርና የውሃ ታንከር ያለው፣ ለንግድና ለዲፕሎማሲ ስራዎች ምቹ።',
    descriptionAr: 'شقة فاخرة بإطلالة بانورامية رائعة في كازانتشيس، مزودة بمولد كهربائي ومياه مستمرة وإنترنت سريع على بعد خطوات من مقر UNECA.'
  },
  {
    id: 'stay-3',
    category: 'stays',
    subType: 'Guest House',
    subTypeAm: 'የእንግዳ ማረፊያ',
    subTypeAr: 'بيت ضيافة بحيرة تانا',
    titleEn: 'Lake Tana Shoreline Eco-Lodge & Guest House',
    titleAm: 'የጣና ሐይቅ ዳርቻ ኢኮ-ሎጅ እና የእንግዳ ማረፊያ',
    titleAr: 'نزل إيكولوجي على ضفاف بحيرة تانا في بحر دار',
    cityId: 'bahirdar',
    cityNameEn: 'Lake Tana, Bahir Dar',
    cityNameAm: 'ጣና ሐይቅ፣ ባህር ዳር',
    cityNameAr: 'بحيرة تانا، بحر دار',
    lat: 11.598,
    lng: 37.382,
    priceETB: 3400,
    priceUnit: 'night',
    rating: 4.92,
    reviewsCount: 44,
    instantBook: false,
    verifiedHost: true,
    trustScore: '97%',
    hostName: 'Hailemariam Assefa',
    hostPhone: '+251 93 345 6789',
    hostTelebirr: '+251 93 345 6789',
    status: 'Available',
    cancellation: 'moderateCancel',
    guestsMax: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ['generator', 'waterTank', 'wifi', 'parking', 'security'],
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80'
    ],
    descriptionEn: 'Serene stone-and-timber waterfront lodge with private boat dock for monastery tours, fresh Nile perch dining, backup generator, and tropical garden.',
    descriptionAm: 'በባህር ዳር የጣና ሐይቅ ዳርቻ የሚገኝ ሰላማዊ የእንግዳ ማረፊያ፣ የጀልባ ጉዞ እና የባህል ምግብ አገልግሎት ያለው።',
    descriptionAr: 'نزل هادئ على ضفاف بحيرة تانا مع مرسى قوارب خاص لزيارة الأديرة التاريخية، وحديقة غناء ومولد كهرباء احتياطي.'
  },
  {
    id: 'stay-4',
    category: 'stays',
    subType: 'Boutique Hotel',
    subTypeAm: 'ቦቲክ ሆቴል',
    subTypeAr: 'فندق تراثي لاليبيلا',
    titleEn: 'Lalibela Mountain View Heritage Suites',
    titleAm: 'የላሊበላ ተራራ እይታ ቅርስ ስዊትስ ሆቴል',
    titleAr: 'أجنحة إطلالة الجبل التراثية في لاليبيلا',
    cityId: 'lalibela',
    cityNameEn: 'Historic Lalibela',
    cityNameAm: 'ታሪካዊ ላሊበላ',
    cityNameAr: 'لاليبيلا التاريخية',
    lat: 12.035,
    lng: 39.043,
    priceETB: 3900,
    priceUnit: 'night',
    rating: 4.97,
    reviewsCount: 67,
    instantBook: true,
    verifiedHost: true,
    trustScore: '100%',
    hostName: 'Kassahun Bekele',
    hostPhone: '+251 94 456 7890',
    hostTelebirr: '+251 94 456 7890',
    status: 'Available',
    cancellation: 'freeCancel',
    guestsMax: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['generator', 'waterTank', 'wifi', 'security', 'ac'],
    images: [
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80'
    ],
    descriptionEn: 'Perched overlooking the Lasta mountains, 8 minutes walk to the 11 rock-hewn UNESCO churches. Includes traditional breakfast, solar backup, and heated showers.',
    descriptionAm: 'ከውብ የላስታ ተራሮች ፊት ለፊት ከውቅር አብያተ ክርስቲያናት ጥቂት ደቂቃዎች ርቀት ላይ የሚገኝ ምርጥ ሆቴል።',
    descriptionAr: 'أجنحة مطلة على جبال لاستا الشاهقة، على بُعد دقائق من كنائس لاليبيلا الصخرية الشهيرة، مع إفطار إثيوبي تقليدي وطاقة شمسية.'
  },
  {
    id: 'stay-5',
    category: 'stays',
    subType: 'Villa',
    subTypeAm: 'ቪላ',
    subTypeAr: 'فيلا بحيرة هواسا',
    titleEn: 'Hawassa Lakeside Sunset Villa with Pool',
    titleAm: 'የሀዋሳ ሐይቅ ፀሐይ መግቢያ ቪላ ከመዋኛ ገንዳ ጋር',
    titleAr: 'فيلا غروب الشمس على ضفاف بحيرة هواسا مع مسبح خاص',
    cityId: 'hawassa',
    cityNameEn: 'Lake Hawassa Promenade',
    cityNameAm: 'የሀዋሳ ሐይቅ ዳርቻ',
    cityNameAr: 'كورنيش بحيرة هواسا',
    lat: 7.058,
    lng: 38.472,
    priceETB: 6800,
    priceUnit: 'night',
    rating: 4.91,
    reviewsCount: 29,
    instantBook: true,
    verifiedHost: true,
    trustScore: '99%',
    hostName: 'Almaz Wolde',
    hostPhone: '+251 95 567 8901',
    hostTelebirr: '+251 95 567 8901',
    status: 'Available',
    cancellation: 'freeCancel',
    guestsMax: 8,
    bedrooms: 4,
    bathrooms: 4,
    amenities: ['generator', 'waterTank', 'wifi', 'kitchen', 'security', 'parking', 'ac'],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=800&q=80'
    ],
    descriptionEn: 'Sprawling lakeside private villa with manicured lawn, infinity plunge pool, water tanks, automatic diesel generator, and view of Mount Tabor.',
    descriptionAm: 'በሀዋሳ ሐይቅ ዳር የሚገኝ ሰፊ ቪላ ከመዋኛ ገንዳ እና ጀነሬተር ጋር፣ ለቤተሰብ እረፍት ፍጹም።',
    descriptionAr: 'فيلا فخمة على شاطئ بحيرة هواسا تضم مسبحاً خاصاً وحديقة شاسعة ومولد كهربائي ديزل وخزانات مياه احتياطية.'
  },

  // ================= WHEELS =================
  {
    id: 'wheel-1',
    category: 'wheels',
    subType: 'SUV 4x4',
    subTypeAm: 'SUV 4x4',
    subTypeAr: 'سيارة دفع رباعي SUV',
    titleEn: 'Toyota Land Cruiser V8 Prado 4x4 with Chauffeur',
    titleAm: 'ቶዮታ ላንድ ክሩዘር ፕራዶ 4x4 ከሹፌር ጋር',
    titleAr: 'تويوتا لاند كروزر برادو 4x4 مع سائق محترف',
    cityId: 'addis',
    cityNameEn: 'Addis Ababa (Nationwide travel)',
    cityNameAm: 'አዲስ አበባ (ለመላው ኢትዮጵያ ጉዞ)',
    cityNameAr: 'أديس أبابا (متاح لجميع مناطق إثيوبيا)',
    lat: 9.03,
    lng: 38.75,
    priceETB: 9500,
    priceUnit: 'day',
    rating: 4.96,
    reviewsCount: 84,
    instantBook: true,
    verifiedHost: true,
    trustScore: '100%',
    hostName: 'Yonas Gebre',
    hostPhone: '+251 91 222 3344',
    hostTelebirr: '+251 91 222 3344',
    status: 'Available',
    cancellation: 'freeCancel',
    guestsMax: 5,
    bedrooms: 0,
    bathrooms: 0,
    amenities: ['ac', 'wifi', 'security'],
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=80'
    ],
    descriptionEn: 'Fully equipped 4x4 Land Cruiser with dual fuel tanks, AC, mobile Wi-Fi, and experienced English/Amharic speaking driver suitable for Highlands, Omo Valley, or Danakil.',
    descriptionAm: 'ለረጅም ጉዞ እና ለተራራማ ቦታዎች ተስማሚ የሆነ ቶዮታ ላንድ ክሩዘር ከታማኝ ሹፌር ጋር።',
    descriptionAr: 'سيارة تويوتا لاند كروزر برادو مجهزة بأحدث وسائل الراحة وتكييف قوي وسائق مرخص يتحدث الإنجليزية والأمهرية مناسبة لجميع التضاريس.'
  },
  {
    id: 'wheel-2',
    category: 'wheels',
    subType: 'Minibus',
    subTypeAm: 'ሚኒባስ',
    subTypeAr: 'حافلة صغيرة تويوتا هايس',
    titleEn: 'Toyota HiAce Luxury 12-Seater Tourist Van',
    titleAm: 'ቶዮታ ሃይኤስ ባለ 12 መቀመጫ የቱሪስት ሚኒባስ',
    titleAr: 'حافلة تويوتا هايس السياحية الفاخرة 12 راكباً',
    cityId: 'bahirdar',
    cityNameEn: 'Bahir Dar & Northern Circuit',
    cityNameAm: 'ባህር ዳር እና የሰሜን መስመር',
    cityNameAr: 'بحر دار والمسار السياحي الشمالي',
    lat: 11.59,
    lng: 37.39,
    priceETB: 7200,
    priceUnit: 'day',
    rating: 4.89,
    reviewsCount: 31,
    instantBook: false,
    verifiedHost: true,
    trustScore: '96%',
    hostName: 'Alemayehu Kassa',
    hostPhone: '+251 92 333 4455',
    hostTelebirr: '+251 92 333 4455',
    status: 'Available',
    cancellation: 'moderateCancel',
    guestsMax: 12,
    bedrooms: 0,
    bathrooms: 0,
    amenities: ['ac', 'security'],
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80'
    ],
    descriptionEn: 'High-roof Toyota HiAce configured for comfort with reclining seats, large luggage space, dual AC, microphone PA system, and veteran Blue Nile falls driver.',
    descriptionAm: 'ለቡድንና ለቤተሰብ ጉዞ ተስማሚ የሆነ ባለ 12 መቀመጫ ሚኒባስ ከአየር ማቀዝቀዣ ጋር።',
    descriptionAr: 'حافلة سياحية مريحة تتسع لـ 12 راكباً مع تكييف مزدوج ومساحة رحبة للحقائب وسائق خبير بالطرق السياحية.'
  },
  {
    id: 'wheel-3',
    category: 'wheels',
    subType: 'Sedan',
    subTypeAm: 'ሴዳን መኪና',
    subTypeAr: 'سيارة سيدان كورولا حديثة',
    titleEn: 'Executive Hyundai Elantra / Toyota Corolla Hybrid',
    titleAm: 'ዘመናዊ ኮሮላ / ኤላንትራ ሴዳን መኪና ለአዲስ አበባ',
    titleAr: 'سيارة سيدان اقتصادية حديثة لمدينة أديس أبابا',
    cityId: 'addis',
    cityNameEn: 'Bole Airport & Addis Downtown',
    cityNameAm: 'ቦሌ አውሮፕላን ማረፊያ እና አዲስ አበባ ከተማ',
    cityNameAr: 'مطار بولي ووسط مدينة أديس أبابا',
    lat: 9.01,
    lng: 38.77,
    priceETB: 3500,
    priceUnit: 'day',
    rating: 4.93,
    reviewsCount: 65,
    instantBook: true,
    verifiedHost: true,
    trustScore: '99%',
    hostName: 'Ermias Berhanu',
    hostPhone: '+251 93 444 5566',
    hostTelebirr: '+251 93 444 5566',
    status: 'Available',
    cancellation: 'freeCancel',
    guestsMax: 4,
    bedrooms: 0,
    bathrooms: 0,
    amenities: ['ac', 'wifi'],
    images: [
      'https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=800&q=80'
    ],
    descriptionEn: 'Pristine city car with unlimited airport pickups, smooth automatic transmission, chilled AC, USB fast chargers, and driver-on-demand option.',
    descriptionAm: 'ለከተማ ውስጥ ጉዞ፣ ለአውሮፕላን ማረፊያ መቀበያ እና ለስብሰባዎች ምቹ ዘመናዊ ሴዳን መኪና።',
    descriptionAr: 'سيارة سيدان أنيقة ومريحة للتنقل داخل العاصمة أديس أبابا واستقبال المطار مع تكييف ممتاز وشواحن سريعة.'
  },

  // ================= EXPERIENCES =================
  {
    id: 'exp-1',
    category: 'experiences',
    subType: 'Cultural Ceremony',
    subTypeAm: 'ባህላዊ ስነ-ስርዓት',
    subTypeAr: 'مراسم القهوة الإثيوبية التراثية',
    titleEn: 'Authentic 3-Round Ethiopian Coffee Ceremony & Food Tasting',
    titleAm: 'የ3 ዙር ባህላዊ የኢትዮጵያ ቡና አፈላል እና የምግብ ቅምሻ',
    titleAr: 'مراسم القهوة الإثيوبية التقليدية الثلاثية مع تذوق المأكولات',
    cityId: 'addis',
    cityNameEn: 'Piazza / Old Town, Addis Ababa',
    cityNameAm: 'ፒያሳ፣ አዲስ አበባ',
    cityNameAr: 'بياتسا التاريخية، أديس أبابا',
    lat: 9.035,
    lng: 38.752,
    priceETB: 1200,
    priceUnit: 'person',
    rating: 4.98,
    reviewsCount: 112,
    instantBook: true,
    verifiedHost: true,
    trustScore: '100%',
    hostName: 'Tigist Hailu',
    hostPhone: '+251 94 555 6677',
    hostTelebirr: '+251 94 555 6677',
    status: 'Available',
    cancellation: 'freeCancel',
    guestsMax: 10,
    bedrooms: 0,
    bathrooms: 0,
    amenities: ['wifi'],
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80'
    ],
    descriptionEn: 'Experience the soul of Ethiopia: raw bean washing, charcoal roasting over frankincense, hand-grinding, and brewing the 3 traditional rounds (Abol, Tona, Baraka) with popcorn and fresh dabo.',
    descriptionAm: 'የኢትዮጵያን እውነተኛ የቡና ባህል የሚለማመዱበት፡ የቡና ማጠብ፣ ማመስ፣ መውቀጥ እና አቦል፣ ቶና፣ በረካ 3 ዙር ከፈንድሻ እና ዳቦ ጋር።',
    descriptionAr: 'عش أصالة الضيافة الإثيوبية مع طقوس غسل البن وتحميصه على الفحم وتصاعد رائحة البخور وإعداد دورات القهوة الثلاث الشهيرة مع الفشار والخبز الطازج.'
  },
  {
    id: 'exp-2',
    category: 'experiences',
    subType: 'Historical Trek',
    subTypeAm: 'ታሪካዊ ጉዞ',
    subTypeAr: 'جولة كنائس لاليبيلا الصخرية',
    titleEn: 'Guided Sacred Lalibela 11 Monolithic Churches & Sunset Chanting',
    titleAm: 'የተቀደሱት 11ዱ የላሊበላ ውቅር አብያተ ክርስቲያናት እና የፀሐይ መግቢያ ዝማሬ',
    titleAr: 'جولة إرشادية في كنائس لاليبيلا الصخرية الـ 11 والتراتيل المسائية',
    cityId: 'lalibela',
    cityNameEn: 'UNESCO Lalibela',
    cityNameAm: 'ዩኔስኮ ላሊበላ',
    cityNameAr: 'موقع التراث العالمي لاليبيلا',
    lat: 12.031,
    lng: 39.041,
    priceETB: 2800,
    priceUnit: 'person',
    rating: 4.99,
    reviewsCount: 95,
    instantBook: true,
    verifiedHost: true,
    trustScore: '100%',
    hostName: 'Deacon Yohannes',
    hostPhone: '+251 95 666 7788',
    hostTelebirr: '+251 95 666 7788',
    status: 'Available',
    cancellation: 'freeCancel',
    guestsMax: 8,
    bedrooms: 0,
    bathrooms: 0,
    amenities: ['security'],
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=80'
    ],
    descriptionEn: 'Deep architectural and spiritual tour of Bete Giyorgis (House of St. George) and all 11 12th-century churches led by an accredited ecclesiastical historian.',
    descriptionAm: 'የቤተ ጊዮርጊስ እና የሁሉም 11 ውቅር አብያተ ክርስቲያናት ጥልቅ የታሪክና የመንፈሳዊ ጉብኝት ከታሪክ ተመራማሪ መሪ ጋር።',
    descriptionAr: 'جولة تاريخية وروحية متعمقة في كنيسة القديس جرجس وجميع الكنائس الـ 11 المنحوتة في الصخر بقيادة مؤرخ معتمد.'
  },
  {
    id: 'exp-3',
    category: 'experiences',
    subType: 'Boat Safari',
    subTypeAm: 'የጀልባ ሳፋሪ',
    subTypeAr: 'سفاري القوارب وسوق الأسماك بحيرة هواسا',
    titleEn: 'Lake Hawassa Hippo Safari & Morning Fish Market Cooking',
    titleAm: 'የሀዋሳ ሐይቅ ጉማሬ ሳፋሪ እና የዓሳ ገበያ ጥብስ ዝግጅት',
    titleAr: 'سفاري أفراس النهر في بحيرة هواسا وتجربة طهي السمك الطازج',
    cityId: 'hawassa',
    cityNameEn: 'Lake Hawassa Port',
    cityNameAm: 'የሀዋሳ ሐይቅ ወደብ',
    cityNameAr: 'ميناء بحيرة هواسا',
    lat: 7.061,
    lng: 38.479,
    priceETB: 1800,
    priceUnit: 'person',
    rating: 4.87,
    reviewsCount: 42,
    instantBook: false,
    verifiedHost: true,
    trustScore: '97%',
    hostName: 'Nebiyu Tulu',
    hostPhone: '+251 96 777 8899',
    hostTelebirr: '+251 96 777 8899',
    status: 'Available',
    cancellation: 'moderateCancel',
    guestsMax: 6,
    bedrooms: 0,
    bathrooms: 0,
    amenities: ['security'],
    images: [
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80'
    ],
    descriptionEn: 'Glide on motor launch alongside wild hippopotamuses, observe marabou storks, and visit the vibrant Hawassa fish market for grilled tilapia with mitmita and lime.',
    descriptionAm: 'በሞተር ጀልባ የሀዋሳ ሐይቅ ጉማሬዎችን መጎብኘት እና ዝነኛውን የሀዋሳ ዓሳ በምጥሚጣና ሎሚ መቅመስ።',
    descriptionAr: 'رحلة بالقارب لمشاهدة أفراس النهر البرية والطيور المائية وزيارة سوق الأسماك الشهير وتذوق سمك البلطي المشوي الطازج.'
  }
];

window.ethiopianCities = ethiopianCities;
window.sponsoredAds = sponsoredAds;
window.listingsData = listingsData;
